export const manufacturers = [
    "Abarth",
    "AC Cars",
    "Acurai",
    "Alfa Romeo",
    "Alpine",
    "Ariel",
    "Aston Martin",
    "Audi",
    "BAC",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "BYD",
    "Cadillac",
    "Caterham",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Cupran",
    "Dacia",
    "Daihatsu",
    "Datsun",
    "Dodge",
    "DS Automobiles",
    "Ferrari",
    "Fiat",
    "Ford",
    "Genesis",
    "GMC",
    "Great Wall Motors",
    "Hennessey",
    "Holden",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Koenigsegg",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
   "Lucid Motors",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "MINI",
    "Mitsubishi",
    "Morgan",
    "Nissan",
    "Noble",
    "Opel",
    "Pagani",
    "Peugeot",
    "Pininfarina",
    "Polestar",
    "Pontiac",
    "Porsche",
    "RAM Trucks",
    "Renault",
    "Rivian",
    "Rolls-Royce",
    "Saab",
    "Saleen",
    "SEAT",
    "Škoda",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Triumph",
    "TVR",
    "Vauxhall",
    "Volkswagen",
    "Volvo",
    "Wiesmann"
  ];
  
  export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
  ];
  
  export const fuels = [
    {
      title: "Fuel",
      value: "",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];
  